"""legacy_schema

Revision ID: 87c050402d09
Revises:
Create Date: 2026-08-05 10:41:21.184729

"""

from collections.abc import Sequence

import sqlalchemy as sa

import newsroom
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87c050402d09"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "new_releases",
        sa.Column("appid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("release_date", newsroom.database.UtcDateTime(), nullable=False),
        sa.Column("review_desc", sa.String(), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("positive_pct", sa.Float(), nullable=False),
        sa.Column("discovered_at", newsroom.database.UtcDateTime(), nullable=False),
        sa.Column("last_seen", newsroom.database.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("appid"),
    )
    op.create_table(
        "news_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_key", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("developer", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("promotion_type", sa.String(), nullable=False),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("current_price", sa.Float(), nullable=True),
        sa.Column("promotion_start", newsroom.database.UtcDateTime(), nullable=True),
        sa.Column("promotion_end", newsroom.database.UtcDateTime(), nullable=True),
        sa.Column("discovered_at", newsroom.database.UtcDateTime(), nullable=False),
        sa.Column("last_seen", newsroom.database.UtcDateTime(), nullable=False),
        sa.Column("confidence_score", sa.Integer(), nullable=False),
        sa.Column("confidence_reasons", sa.JSON(), nullable=False),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_news_events_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_news_events_event_key"), ["event_key"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_news_events_promotion_type"), ["promotion_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_events_source"), ["source"], unique=False)

    op.create_table(
        "source_health",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("last_attempt_at", newsroom.database.UtcDateTime(), nullable=False),
        sa.Column("last_success_at", newsroom.database.UtcDateTime(), nullable=True),
        sa.Column("last_status", sa.String(), nullable=False),
        sa.Column("last_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "steam_deals",
        sa.Column("appid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("discount_percent", sa.Integer(), nullable=False),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("final_price", sa.Float(), nullable=True),
        sa.Column("review_desc", sa.String(), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("positive_pct", sa.Float(), nullable=False),
        sa.Column("discount_end", newsroom.database.UtcDateTime(), nullable=True),
        sa.Column("discovered_at", newsroom.database.UtcDateTime(), nullable=False),
        sa.Column("last_seen", newsroom.database.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("appid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("steam_deals")
    op.drop_table("source_health")
    with op.batch_alter_table("news_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_events_source"))
        batch_op.drop_index(batch_op.f("ix_news_events_promotion_type"))
        batch_op.drop_index(batch_op.f("ix_news_events_event_key"))
        batch_op.drop_index(batch_op.f("ix_news_events_category"))

    op.drop_table("news_events")
    op.drop_table("new_releases")
    # ### end Alembic commands ###
