"""add_subscription_columns

Revision ID: d2610dba96ff
Revises: 87c050402d09
Create Date: 2026-08-05 10:42:11.938663

"""

from collections.abc import Sequence

import sqlalchemy as sa

import newsroom
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2610dba96ff"
down_revision: str | Sequence[str] | None = "87c050402d09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("access_model", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("ownership_model", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("service", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("available_from", newsroom.database.UtcDateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("available_until", newsroom.database.UtcDateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("claim_deadline", newsroom.database.UtcDateTime(), nullable=True)
        )
        batch_op.add_column(sa.Column("day_one", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("tiers", sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column("platforms", sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column("regions", sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column("storefronts", sa.JSON(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_news_events_access_model"), ["access_model"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_news_events_ownership_model"), ["ownership_model"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_events_service"), ["service"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_events_service"))
        batch_op.drop_index(batch_op.f("ix_news_events_ownership_model"))
        batch_op.drop_index(batch_op.f("ix_news_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_news_events_access_model"))
        batch_op.drop_column("storefronts")
        batch_op.drop_column("regions")
        batch_op.drop_column("platforms")
        batch_op.drop_column("tiers")
        batch_op.drop_column("day_one")
        batch_op.drop_column("claim_deadline")
        batch_op.drop_column("available_until")
        batch_op.drop_column("available_from")
        batch_op.drop_column("service")
        batch_op.drop_column("ownership_model")
        batch_op.drop_column("access_model")
        batch_op.drop_column("event_type")

    # ### end Alembic commands ###
